#build base image with all npm package pre installed
# docker build . -f Dockerfile.base -t base-potal-plus-fe
FROM node:18 As build

WORKDIR /usr/src/app

COPY package.json package-lock.json ./

RUN npm install

# COPY . .

# #RUN npm run build-prod
# RUN npm run build

# FROM nginx:1.15.8-alpine

# COPY --from=build /usr/src/app/dist /usr/share/nginx/html

# EXPOSE 80