export const environment = {
    production: true,
    hmr: false,
    staging: false,
    // url: 'http://customerportalapi.nextlogistics.com.au',
    receivingUrl:window["env"]["receivingUrl"],
    url: window["env"]["apiUrl"],
    hUrl: window["env"]["hUrl"],
    phUrl: window["env"]["phUrl"],
    csurl: window["env"]["csurl"],
    inProgressTime: window["env"]["inProgressTime"],
    reUploadUrl: window["env"]["reUploadUrl"],
    refreshTimeForFilelog: window["env"]["refreshTimeForFilelog"],
    // url: 'https://fbsgateway.greenmushroom-bbce887c.australiaeast.azurecontainerapps.io',
    tokenKey: 'accessToken',
};
